# Generated by Django 5.2.3 on 2025-09-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='updated_at',
        ),
    ]
